export const SET_COMPUTER_VALUE = "SET_COMPUTER_VALUE"
export const SET_USER_VALUE = "SET_USER_VALUE"
export const PUSH = "PUSH"
export const RESET = "RESET"
export const SET_TMP_USER_VALUE = "SET_TMP_USER_VALUE"
export const WINNER_IS = "WINNER_IS"
export const START_AT = "START_AT"